added GA
DSchau/css-in-js-playground pull request #64
Opened 2017-10-05 17:18 UTC by bossbossk20

added Google Analytic using react-ga

2017-10-05 17:20 UTC, bossbossk20 commented
#61

2017-10-05 17:20 UTC, DSchau commented
Deploy preview ready!

Built with commit 0ca1ced9a9df42776c4d7554dd9fade83314e960

https://deploy-preview-64--violinist-oxygen-57835.netlify.com

2017-10-05 18:04 UTC, DSchau requested changes
I'm open to the idea of using react-ga, but only if I'm getting (extra) value out of it vs. just the inline script

I hate to be a pain, but I think I'd prefer the inline script route in src/index.html (which is easier too).

Want to give that a shot?

2017-10-05 18:04 UTC, DSchau commented on tsconfig.json
> +    "allowSyntheticDefaultImports": true,
This change breaks a few other things, I believe!

2017-10-05 19:27 UTC, DSchau approved these changes

2017-10-05 19:28 UTC, DSchau commented
@bossbossk20 could you "allow edits from maintainers" in the right  hand side of the PR?

I would like to use this script, otherwise this is perfect :)

```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
```

2017-10-05 20:18 UTC, DSchau commented
@bossbossk20 also sorry for the lack of direction, should've been way clearer up-front what I was hoping for! Thank you again :)

2017-10-06 04:06 UTC, bossbossk20 commented
I did it @DSchau

2017-10-07 17:06 UTC, bossbossk20 commented
hey

2017-10-07 18:41 UTC, DSchau requested changes
Why are there other file edits in this PR? Also react-ga is included in package.json

2017-10-08 06:50 UTC, DSchau approved these changes

2017-10-08 06:50 UTC, merged